# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM golang:1.24-bookworm

# Install Rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

# Install build dependencies
RUN apt-get update && apt-get install -y \
    curl \
    tar \
    g++ \
    libssl-dev \
    pkg-config \
    clang \
    libclang-dev \
    git \
    protobuf-compiler \
    && rm -rf /var/lib/apt/lists/*

# Install CMake 3.28.3
RUN curl -sSL https://github.com/Kitware/CMake/releases/download/v3.28.3/cmake-3.28.3-linux-x86_64.tar.gz -o cmake.tar.gz \
    && tar -zxvf cmake.tar.gz -C /opt/ \
    && rm cmake.tar.gz
ENV PATH="/opt/cmake-3.28.3-linux-x86_64/bin:${PATH}"

# Install cbindgen and bindgen-cli and protoc-gen-go
RUN cargo install cbindgen bindgen-cli
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.11
ENV PATH="/root/go/bin:${PATH}"

WORKDIR /app
COPY . .

# Generate FFI headers and build Rust in debug mode for faster tests
RUN ./generate_ffi_headers.sh
RUN --mount=type=cache,target=/root/.cargo/registry \
    --mount=type=cache,target=/root/.cargo/git \
    --mount=type=cache,target=/app/target \
    cargo build --workspace

# The entrypoint runs all tests and exits with the corresponding code
ENTRYPOINT ["/bin/bash", "-c", "set -o pipefail && cargo test --workspace && GOCACHE=/tmp/go-cache go test -v ./... && GOCACHE=/tmp/go-cache go test -v -race -tags integration ./..."]
